---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "10"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-lts-3.4 PERCY_TOKEN="skip percy"
    - env: EMBER_TRY_SCENARIO=ember-lts-3.8 PERCY_TOKEN="skip percy"
    - env: EMBER_TRY_SCENARIO=ember-canary PERCY_TOKEN="skip percy"

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      install:
        - yarn install --non-interactive
      script:
        - yarn lint:hbs
        - yarn lint:js
        - yarn test

    - name: "Floating Dependencies"
      script:
        - yarn test

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-3.4 PERCY_TOKEN="skip percy"
    - env: EMBER_TRY_SCENARIO=ember-lts-3.8 PERCY_TOKEN="skip percy"
    - env: EMBER_TRY_SCENARIO=ember-release PERCY_TOKEN="skip percy"
    - env: EMBER_TRY_SCENARIO=ember-beta PERCY_TOKEN="skip percy"
    - env: EMBER_TRY_SCENARIO=ember-canary PERCY_TOKEN="skip percy"

    - stage: deploy-gh-pages
      name: "Deploy to Github Pages"
      if: branch = master AND type != pull_request
      script:
        - npm run build -- -prod # build app and prepare dist folder
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
        local-dir: dist
        verbose: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then PERCY_TOKEN="skip percy"; fi'

install:
  - yarn install --no-lockfile --non-interactive

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
